import "./globals.css";
import { Inter } from "next/font/google";
import Provider from "@/components/Provider";
import { Root } from "postcss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
};
export default RootLayout;
